version: '3'
services:
  mariadb:
    build: requirements/mariadb
    volumes:
      - /home/perol/data/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - backend
    restart: always

networks:
  frontend:
  backend: